name: docker-executor-monitor
on:
  push:
    branches:
      - 'main'
      - 'develop'
    tags:
      - '*'
jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Executor-Monitor
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./executor-monitor/Dockerfile
          push: true
          tags: ghcr.io/linkedpipes/etl-executor-monitor:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
